"""
PRIMEnergeia — Grid Engineer Outputs Catalog
================================================
Showcases all PRIMEnergeia outputs that grid engineers can
plug directly into SCADA / EMS / BMS systems.

6 output categories:
  1. Optimal Dispatch Schedule
  2. Frequency Response Signals
  3. Price Forecast & Arbitrage Targets
  4. Battery SOC/SOH Telemetry
  5. Ancillary Services Bids
  6. Savings & Revenue Reports

PRIMEnergeia S.A.S. — Grid Optimization Division
"""
# --- DEMO/LIVE Mode Banner ---
import sys as _sys, os as _os
_root = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
if _root not in _sys.path: _sys.path.insert(0, _root)
try:
    from lib.mode_gate import show_mode_banner
    show_mode_banner()
except Exception: pass
try:
    from lib.granas_handshake import show_handshake_sidebar
    show_handshake_sidebar()
except Exception: pass
# --- End Banner ---

import streamlit as st
import numpy as np
import pandas as pd
import sys, os
import json
from datetime import datetime, timedelta

# Resolve project imports
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _ROOT)
sys.path.insert(0, os.path.join(_ROOT, "markets"))

from markets.ercot.dispatch_ercot import run_ercot_coopt
from markets.sen.dispatch_sen import run_sen_coopt
from markets.mibel.dispatch_mibel import run_mibel_coopt

# ═══════════════════════════════════════════════════════════════
#  PAGE STYLES
# ═══════════════════════════════════════════════════════════════

st.markdown("""<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap');

[data-testid="stMetricValue"] {font-size: 24px !important; font-weight: 700}
[data-testid="stMetricLabel"] {font-size: 12px !important; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px}
[data-testid="stMetricDelta"] {font-size: 13px !important}
.block-container {padding-top: 2rem}

.output-card {
    background: linear-gradient(135deg, #0d1520, #111b2a);
    border: 1px solid #1a2744;
    border-radius: 12px;
    padding: 24px 28px;
    margin-bottom: 14px;
    transition: border-color 0.3s, box-shadow 0.3s, transform 0.2s;
}
.output-card:hover {
    border-color: #00d1ff;
    box-shadow: 0 0 20px rgba(0,209,255,0.12);
    transform: translateY(-2px);
}
.output-title {
    font-family: 'JetBrains Mono', monospace;
    font-size: 17px;
    font-weight: 700;
    margin-bottom: 6px;
}
.output-desc {
    color: #94a3b8;
    font-size: 13px;
    line-height: 1.5;
}
.output-badge {
    display: inline-block;
    background: rgba(0, 209, 255, 0.12);
    color: #00d1ff;
    font-family: 'JetBrains Mono', monospace;
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: 3px 8px;
    border-radius: 4px;
    margin-right: 6px;
    margin-top: 10px;
}
.output-badge-green {
    display: inline-block;
    background: rgba(0, 255, 136, 0.12);
    color: #00ff88;
    font-family: 'JetBrains Mono', monospace;
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: 3px 8px;
    border-radius: 4px;
    margin-right: 6px;
    margin-top: 10px;
}
.output-badge-amber {
    display: inline-block;
    background: rgba(255, 193, 7, 0.12);
    color: #FFC107;
    font-family: 'JetBrains Mono', monospace;
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: 3px 8px;
    border-radius: 4px;
    margin-right: 6px;
    margin-top: 10px;
}
.protocol-card {
    background: linear-gradient(135deg, #0a1628, #0d1f3c);
    border: 1px solid rgba(99, 102, 241, 0.25);
    border-radius: 10px;
    padding: 20px;
    margin-bottom: 12px;
}
.section-header {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    letter-spacing: 2px;
    font-weight: 600;
    margin-bottom: 4px;
}
</style>""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════
#  HEADER
# ═══════════════════════════════════════════════════════════════
st.markdown("## 🔌 Grid Engineer Outputs Catalog")
st.markdown("""
<div style='background: linear-gradient(135deg, #0a1628 0%, #0d1f3c 50%, #0f3460 100%);
     padding: 20px 28px; border-radius: 12px; margin-bottom: 24px;
     border: 1px solid rgba(0, 209, 255, 0.25)'>
<span style='font-size: 13px; color: #00d1ff; font-weight: 600; letter-spacing: 1px'>INTEGRATION-READY OUTPUTS</span><br>
<span style='font-size: 18px; color: white; font-weight: 600'>Plug PRIMEnergeia directly into your SCADA · EMS · BMS · Trading Desk</span><br>
<span style='font-size: 13px; color: #94a3b8'>Every output below is generated by the HJB dispatch engine across 17 global ISOs.
Download as CSV/JSON or consume via API for real-time integration.</span>
</div>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════════════════
#  OUTPUT CATALOG — 6 CARDS
# ═══════════════════════════════════════════════════════════════

st.markdown("### 📋 Output Catalog")

OUTPUTS = [
    {
        "icon": "⚡", "title": "Optimal Dispatch Schedule",
        "color": "#00d1ff",
        "desc": "Hourly MW charge/discharge setpoints computed by the HJB two-pass lookahead optimizer. "
                "Direct feed for BESS controllers and EMS load-following systems.",
        "badges": ["CSV", "JSON", "SCADA API"],
        "fields": "Hour · Strategy (CHARGE / DISCHARGE / HOLD+AS) · Dispatch MW · DA Price · RT Price",
        "use_case": "EMS load scheduling, BESS charge/discharge controllers, day-ahead commitment",
    },
    {
        "icon": "🌊", "title": "Frequency Response Signals",
        "color": "#26C6DA",
        "desc": "Swing Equation solver telemetry — grid frequency, RoCoF (df/dt), and synthetic inertia "
                "injection u(t). Tuned per-market: 50 Hz (MIBEL/ENTSO-E) or 60 Hz (ERCOT/SEN).",
        "badges": ["REAL-TIME", "CSV", "IEC 61850"],
        "fields": "Timestamp · Frequency (Hz) · RoCoF (Hz/s) · Inertia u (p.u.) · Cumulative Savings",
        "use_case": "Governor control loops, synthetic inertia inverters, under-frequency relay settings",
    },
    {
        "icon": "💰", "title": "Price Forecast & Arbitrage Targets",
        "color": "#FFD700",
        "desc": "Day-ahead and real-time LMP forecasts with pre-identified charge/discharge windows. "
                "Includes spike detection thresholds and spread ratios per hour.",
        "badges": ["CSV", "JSON", "TRADING API"],
        "fields": "Hour · DA LMP ($/MWh) · RT LMP ($/MWh) · Spread Ratio · Action Tag · Spike Flag",
        "use_case": "Trading desk auto-bidding, merchant plant scheduling, congestion analysis",
    },
    {
        "icon": "🔋", "title": "Battery SOC / SOH Telemetry",
        "color": "#8b5cf6",
        "desc": "Full state-of-charge trajectory, state-of-health degradation tracking, cycle count, "
                "and estimated remaining battery life. Degradation-aware optimization.",
        "badges": ["CSV", "JSON", "BMS FEED"],
        "fields": "Hour · SOC (%) · SOH · Cycle Count · Degradation Cost ($) · Est. Life (years)",
        "use_case": "BMS integration, predictive maintenance scheduling, warranty tracking",
    },
    {
        "icon": "🛡️", "title": "Ancillary Services Bids",
        "color": "#00ff88",
        "desc": "Per-interval capacity and price bids for RegUp, RegDown, and Responsive Reserve Service (RRS). "
                "Optimized to maximize ancillary revenue during HOLD periods.",
        "badges": ["CSV", "JSON", "ISO PORTAL"],
        "fields": "Hour · Service (RegUp/RegDown/RRS) · Capacity (MW) · Price ($/MW) · Revenue ($)",
        "use_case": "ISO ancillary market auto-bidding, reserve obligation compliance",
    },
    {
        "icon": "📊", "title": "Savings & Revenue Reports",
        "color": "#F1C40F",
        "desc": "Capital recovery analysis — total uplift vs baseline, royalty split, MWh gap quantification, "
                "and annual projections. PDF-ready for regulatory filings.",
        "badges": ["PDF", "JSON", "MARKDOWN"],
        "fields": "Net Profit · Energy Revenue · Ancillary Revenue · Uplift % · Degradation Cost · Annual Proj.",
        "use_case": "Finance systems, regulatory compliance filings, investor reporting",
    },
]

# Render in 2-column grid
for row_start in range(0, len(OUTPUTS), 2):
    cols = st.columns(2)
    for i, col in enumerate(cols):
        idx = row_start + i
        if idx >= len(OUTPUTS):
            break
        o = OUTPUTS[idx]
        badges_html = "".join(
            f"<span class='output-badge'>{b}</span>" for b in o["badges"]
        )
        with col:
            st.markdown(f"""
            <div class='output-card'>
                <div class='output-title' style='color: {o["color"]};'>{o["icon"]} {o["title"]}</div>
                <div class='output-desc'>{o["desc"]}</div>
                <div style='margin-top: 8px; font-size: 12px; color: #64748b;'>
                    <strong style='color: #94a3b8;'>Fields:</strong> {o["fields"]}
                </div>
                <div style='margin-top: 6px; font-size: 12px; color: #64748b;'>
                    <strong style='color: #94a3b8;'>Use Case:</strong> {o["use_case"]}
                </div>
                <div>{badges_html}</div>
            </div>
            """, unsafe_allow_html=True)

st.divider()

# ═══════════════════════════════════════════════════════════════
#  LIVE DEMO GENERATOR
# ═══════════════════════════════════════════════════════════════
st.markdown("### 🚀 Live Output Generator")
st.markdown("""
<div style='color: #94a3b8; font-size: 13px; margin-bottom: 16px;'>
Run the HJB dispatch engine and preview all 6 output streams below.
Download any output as CSV or JSON for direct integration.
</div>
""", unsafe_allow_html=True)

cfg1, cfg2, cfg3 = st.columns(3)
market = cfg1.selectbox("Market", [
    "ERCOT (Texas)", "SEN (Mexico)", "MIBEL (Iberia)"
], key="go_market")
fleet_mw = cfg2.number_input("Fleet Capacity (MW)", 10, 5000, 100, 10, key="go_fleet")
battery_mwh = cfg3.number_input("Battery Storage (MWh)", 10, 20000, 400, 50, key="go_batt")

hours = st.select_slider("Simulation Horizon", options=[24, 48, 72, 120, 168],
                          value=168,
                          format_func=lambda h: f"{h}h ({h//24}d)",
                          key="go_hours")

run_clicked = st.button("⚡ Generate Sample Outputs", type="primary", use_container_width=True)

if run_clicked:
    with st.spinner("Running HJB two-pass dispatch optimizer..."):
        if "ERCOT" in market:
            result = run_ercot_coopt(fleet_mw=fleet_mw, battery_mwh=battery_mwh, hours=hours)
            curr, sym = "USD", "$"
        elif "SEN" in market:
            result = run_sen_coopt(fleet_mw=fleet_mw, battery_mwh=battery_mwh, hours=hours)
            curr, sym = "MXN", "MXN$"
        else:
            result = run_mibel_coopt(fleet_mw=fleet_mw, battery_mwh=battery_mwh, hours=hours)
            curr, sym = "EUR", "€"

    st.success(f"✅ Dispatch complete — {result.hours} hours optimized")

    # ─── Derive all output streams ──────────────────────────

    # Map currency-agnostic fields
    if "ERCOT" in market:
        net_profit = result.net_profit_usd
        energy_rev = result.energy_revenue_usd
        anc_rev = result.ancillary_revenue_usd
        total_rev = result.total_revenue_usd
        deg_cost = result.degradation_cost_usd
        baseline_rev = result.baseline_revenue_usd
    elif "SEN" in market:
        net_profit = result.net_profit_mxn
        energy_rev = result.energy_revenue_mxn
        anc_rev = result.cel_revenue_mxn
        total_rev = result.total_revenue_mxn
        deg_cost = result.degradation_cost_mxn
        baseline_rev = getattr(result, 'baseline_revenue_mxn', 0)
    else:
        net_profit = result.net_profit_eur
        energy_rev = result.energy_revenue_eur
        anc_rev = result.carbon_savings_eur
        total_rev = result.total_revenue_eur
        deg_cost = result.degradation_cost_eur
        baseline_rev = getattr(result, 'baseline_revenue_eur', 0)

    hrs = list(range(result.hours))
    now = datetime.now()
    timestamps = [(now + timedelta(hours=h)).strftime("%Y-%m-%d %H:%M") for h in hrs]

    # ─── TAB OUTPUTS ────────────────────────────────────────
    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
        "⚡ Dispatch Schedule",
        "🌊 Frequency Signals",
        "💰 Price & Arbitrage",
        "🔋 Battery Telemetry",
        "🛡️ Ancillary Bids",
        "📊 Revenue Report",
    ])

    # ═══ OUTPUT 1: DISPATCH SCHEDULE ═══
    with tab1:
        st.markdown("#### ⚡ Optimal Dispatch Schedule")
        dispatch_df = pd.DataFrame({
            "Timestamp": timestamps,
            "Hour": hrs,
            "Strategy": result.strategy,
            "Dispatch_MW": np.round(result.dispatch_mw, 2),
            "DA_Price": np.round(result.da_prices, 2),
            "RT_Price": np.round(result.rt_prices, 2),
        })
        st.dataframe(dispatch_df, use_container_width=True, hide_index=True, height=350)

        # KPIs
        m1, m2, m3, m4 = st.columns(4)
        charge_h = sum(1 for s in result.strategy if "CHARGE" in s or "CARGA" in s)
        discharge_h = sum(1 for s in result.strategy if "DISCHARGE" in s or "DESCARGA" in s)
        hold_h = result.hours - charge_h - discharge_h
        m1.metric("Charge Hours", f"{charge_h}h")
        m2.metric("Discharge Hours", f"{discharge_h}h")
        m3.metric("Hold + AS Hours", f"{hold_h}h")
        m4.metric("Uplift", f"{result.uplift_pct:+.1f}%")

        # Downloads
        d1, d2 = st.columns(2)
        d1.download_button("📥 Download CSV", dispatch_df.to_csv(index=False),
                           f"dispatch_schedule_{market.split()[0].lower()}.csv",
                           "text/csv", use_container_width=True)
        d2.download_button("📥 Download JSON",
                           dispatch_df.to_json(orient="records", indent=2),
                           f"dispatch_schedule_{market.split()[0].lower()}.json",
                           "application/json", use_container_width=True)

    # ═══ OUTPUT 2: FREQUENCY RESPONSE SIGNALS ═══
    with tab2:
        st.markdown("#### 🌊 Frequency Response Signals")
        st.info("Simulated Swing Equation telemetry — matches your market's frequency standard.")

        # Generate frequency telemetry (synthetic but physically consistent)
        f_nom = 50.0 if "MIBEL" in market else 60.0
        H = 6.0 if "MIBEL" in market else (5.0 if "SEN" in market else 4.5)
        D = 2.5 if "MIBEL" in market else (2.0 if "SEN" in market else 1.8)
        rng = np.random.RandomState(42)
        n_points = result.hours * 10  # 6-min resolution within each hour
        freq = np.full(n_points, f_nom)
        rocof = np.zeros(n_points)
        inertia_u = np.zeros(n_points)
        savings_cum = np.zeros(n_points)
        save_total = 0.0
        dt = 0.1

        for i in range(1, n_points):
            p_e_noise = rng.normal(0, 0.005)
            error = f_nom - freq[i - 1]
            u = max(0, error * 500.0)
            M_eff = 2 * H + u
            df_dt = (1.0 - (1.0 + p_e_noise) - D * (freq[i - 1] - f_nom)) / M_eff
            freq[i] = freq[i - 1] + df_dt * dt
            rocof[i] = df_dt
            inertia_u[i] = u
            penalty_thresh = 49.96 if f_nom == 50 else 59.97
            if freq[i] < penalty_thresh:
                save_total += abs(error) * 280000 * dt
            savings_cum[i] = save_total

        # Downsample to hourly for the table
        step = max(1, n_points // result.hours)
        freq_df = pd.DataFrame({
            "Timestamp": timestamps,
            "Frequency_Hz": np.round(freq[::step][:result.hours], 4),
            "RoCoF_Hz_s": np.round(rocof[::step][:result.hours], 6),
            "Inertia_u_pu": np.round(inertia_u[::step][:result.hours], 4),
            "Cumulative_Savings": np.round(savings_cum[::step][:result.hours], 2),
        })
        st.dataframe(freq_df, use_container_width=True, hide_index=True, height=300)

        fm1, fm2, fm3 = st.columns(3)
        fm1.metric("Nominal Frequency", f"{f_nom:.0f} Hz")
        fm2.metric("Inertia Constant H", f"{H:.1f} s")
        fm3.metric("Damping D", f"{D:.1f}")

        fd1, fd2 = st.columns(2)
        fd1.download_button("📥 Download CSV", freq_df.to_csv(index=False),
                            f"frequency_signals_{market.split()[0].lower()}.csv",
                            "text/csv", use_container_width=True)
        fd2.download_button("📥 Download JSON",
                            freq_df.to_json(orient="records", indent=2),
                            f"frequency_signals_{market.split()[0].lower()}.json",
                            "application/json", use_container_width=True)

    # ═══ OUTPUT 3: PRICE FORECAST & ARBITRAGE ═══
    with tab3:
        st.markdown("#### 💰 Price Forecast & Arbitrage Targets")
        spread = np.where(result.da_prices > 0,
                          result.rt_prices / np.maximum(result.da_prices, 0.01), 0)
        spike_flag = result.rt_prices > 100

        price_df = pd.DataFrame({
            "Timestamp": timestamps,
            "Hour": hrs,
            "DA_LMP": np.round(result.da_prices, 2),
            "RT_LMP": np.round(result.rt_prices, 2),
            "Spread_Ratio": np.round(spread, 2),
            "Action": result.strategy,
            "Spike_Flag": spike_flag,
        })
        st.dataframe(price_df, use_container_width=True, hide_index=True, height=350)

        pm1, pm2, pm3, pm4 = st.columns(4)
        pm1.metric("Avg DA Price", f"{sym}{np.mean(result.da_prices):.2f}/MWh")
        pm2.metric("Avg RT Price", f"{sym}{np.mean(result.rt_prices):.2f}/MWh")
        pm3.metric("Max Spread", f"{np.max(spread):.1f}x")
        pm4.metric("Spikes Detected", f"{int(np.sum(spike_flag))}")

        pd1, pd2 = st.columns(2)
        pd1.download_button("📥 Download CSV", price_df.to_csv(index=False),
                            f"price_arbitrage_{market.split()[0].lower()}.csv",
                            "text/csv", use_container_width=True)
        pd2.download_button("📥 Download JSON",
                            price_df.to_json(orient="records", indent=2),
                            f"price_arbitrage_{market.split()[0].lower()}.json",
                            "application/json", use_container_width=True)

    # ═══ OUTPUT 4: BATTERY TELEMETRY ═══
    with tab4:
        st.markdown("#### 🔋 Battery SOC / SOH Telemetry")
        soc_series = result.battery_soc[:result.hours]
        soh_start = result.battery_soh_start
        soh_end = result.battery_soh_end
        soh_loss = soh_start - soh_end
        soh_per_hour = soh_loss / max(result.hours, 1)
        cycle_est = soh_loss / 0.00015 if soh_loss > 0 else 0

        battery_df = pd.DataFrame({
            "Timestamp": timestamps,
            "Hour": hrs,
            "SOC_pct": np.round(soc_series * 100, 2),
            "SOH": np.round(np.linspace(soh_start, soh_end, result.hours), 6),
            "Cycle_Count_Est": np.round(np.linspace(0, cycle_est, result.hours), 2),
            "Degradation_Cost": np.round(
                np.linspace(0, deg_cost, result.hours), 2
            ),
        })
        st.dataframe(battery_df, use_container_width=True, hide_index=True, height=300)

        bm1, bm2, bm3, bm4 = st.columns(4)
        bm1.metric("SOH Start", f"{soh_start:.4f}")
        bm2.metric("SOH End", f"{soh_end:.4f}",
                    delta=f"{(soh_end - soh_start)*100:.3f}%")
        bm3.metric("Est. Cycles", f"{cycle_est:.1f}")
        annual_soh = soh_per_hour * 8760
        battery_life = 0.2 / annual_soh if annual_soh > 0 else 99
        bm4.metric("Est. Battery Life", f"{battery_life:.1f} yrs")

        bd1, bd2 = st.columns(2)
        bd1.download_button("📥 Download CSV", battery_df.to_csv(index=False),
                            f"battery_telemetry_{market.split()[0].lower()}.csv",
                            "text/csv", use_container_width=True)
        bd2.download_button("📥 Download JSON",
                            battery_df.to_json(orient="records", indent=2),
                            f"battery_telemetry_{market.split()[0].lower()}.json",
                            "application/json", use_container_width=True)

    # ═══ OUTPUT 5: ANCILLARY BIDS ═══
    with tab5:
        st.markdown("#### 🛡️ Ancillary Services Bids")
        reg_up_price = np.maximum(result.da_prices * 0.15, 8.0)
        reg_down_price = np.maximum(result.da_prices * 0.05, 3.0)
        rrs_price_arr = np.maximum(result.da_prices * 0.08, 5.0)

        as_capacity = min(fleet_mw * 0.2, battery_mwh / 4 * 0.3)

        anc_rows = []
        for h in hrs:
            if "HOLD" in result.strategy[h] or "AS" in result.strategy[h]:
                anc_rows.append({
                    "Timestamp": timestamps[h], "Hour": h,
                    "Service": "RRS",
                    "Capacity_MW": round(as_capacity, 1),
                    "Price_per_MW": round(rrs_price_arr[h], 2),
                    "Revenue": round(as_capacity * rrs_price_arr[h], 2),
                })
                anc_rows.append({
                    "Timestamp": timestamps[h], "Hour": h,
                    "Service": "RegUp",
                    "Capacity_MW": round(as_capacity * 0.5, 1),
                    "Price_per_MW": round(reg_up_price[h], 2),
                    "Revenue": round(as_capacity * 0.5 * reg_up_price[h], 2),
                })
                anc_rows.append({
                    "Timestamp": timestamps[h], "Hour": h,
                    "Service": "RegDown",
                    "Capacity_MW": round(as_capacity * 0.3, 1),
                    "Price_per_MW": round(reg_down_price[h], 2),
                    "Revenue": round(as_capacity * 0.3 * reg_down_price[h], 2),
                })

        anc_df = pd.DataFrame(anc_rows) if anc_rows else pd.DataFrame(
            columns=["Timestamp", "Hour", "Service", "Capacity_MW", "Price_per_MW", "Revenue"]
        )
        st.dataframe(anc_df, use_container_width=True, hide_index=True, height=350)

        am1, am2, am3 = st.columns(3)
        am1.metric("Total AS Revenue", f"{sym}{anc_rev:,.0f}")
        am2.metric("AS Hours", f"{len(set(r['Hour'] for r in anc_rows)) if anc_rows else 0}h")
        am3.metric("Max RRS Capacity", f"{as_capacity:.1f} MW")

        ad1, ad2 = st.columns(2)
        ad1.download_button("📥 Download CSV", anc_df.to_csv(index=False),
                            f"ancillary_bids_{market.split()[0].lower()}.csv",
                            "text/csv", use_container_width=True)
        ad2.download_button("📥 Download JSON",
                            anc_df.to_json(orient="records", indent=2),
                            f"ancillary_bids_{market.split()[0].lower()}.json",
                            "application/json", use_container_width=True)

    # ═══ OUTPUT 6: REVENUE REPORT ═══
    with tab6:
        st.markdown("#### 📊 Savings & Revenue Report")

        rm1, rm2, rm3, rm4 = st.columns(4)
        rm1.metric("Net Profit", f"{sym}{net_profit:,.0f}")
        rm2.metric("Energy Revenue", f"{sym}{energy_rev:,.0f}")
        rm3.metric("Ancillary Revenue", f"{sym}{anc_rev:,.0f}")
        rm4.metric("Uplift vs Baseline", f"{result.uplift_pct:+.1f}%")

        rm5, rm6, rm7, rm8 = st.columns(4)
        rm5.metric("Total Revenue", f"{sym}{total_rev:,.0f}")
        rm6.metric("Degradation Cost", f"{sym}{deg_cost:,.0f}")
        weekly_factor = result.hours / 168
        annual_net = (net_profit / max(1, weekly_factor)) * 52
        rm7.metric("Annual Projection", f"{sym}{annual_net:,.0f}")
        rm8.metric("Battery SOH", f"{soh_end:.4f}")

        report_json = {
            "generated": datetime.now().isoformat(),
            "market": market,
            "fleet_mw": fleet_mw,
            "battery_mwh": battery_mwh,
            "hours": result.hours,
            "currency": curr,
            "results": {
                "net_profit": net_profit,
                "energy_revenue": energy_rev,
                "ancillary_revenue": anc_rev,
                "total_revenue": total_rev,
                "degradation_cost": deg_cost,
                "uplift_pct": result.uplift_pct,
                "battery_soh_start": soh_start,
                "battery_soh_end": soh_end,
            },
            "annual_projection": {
                "net_profit": round(annual_net, 2),
            },
        }

        rd1, rd2 = st.columns(2)
        rd1.download_button("📥 Download Report JSON",
                            json.dumps(report_json, indent=2),
                            f"revenue_report_{market.split()[0].lower()}.json",
                            "application/json", use_container_width=True)

        # Markdown report
        report_md = f"""# PRIMEnergeia — Grid Engineer Revenue Report
**Generated:** {datetime.now().strftime('%B %d, %Y %H:%M')}
**Market:** {market} | **Fleet:** {fleet_mw} MW | **Battery:** {battery_mwh} MWh

---

| Metric | Value |
|--------|-------|
| Net Profit | {sym}{net_profit:,.0f} |
| Energy Revenue | {sym}{energy_rev:,.0f} |
| Ancillary Revenue | {sym}{anc_rev:,.0f} |
| Total Revenue | {sym}{total_rev:,.0f} |
| Degradation Cost | {sym}{deg_cost:,.0f} |
| Uplift vs Baseline | {result.uplift_pct:+.1f}% |
| Battery SOH | {soh_start:.4f} → {soh_end:.4f} |
| Annual Projection | {sym}{annual_net:,.0f} |

---
*PRIMEnergeia S.A.S. — Grid Optimization Division*
"""
        rd2.download_button("📥 Download Report MD", report_md,
                            f"revenue_report_{market.split()[0].lower()}.md",
                            "text/markdown", use_container_width=True)

st.divider()

# ═══════════════════════════════════════════════════════════════
#  INTEGRATION GUIDE
# ═══════════════════════════════════════════════════════════════
st.markdown("### 🔧 Integration Guide")
st.markdown("""
<div style='color: #94a3b8; font-size: 13px; margin-bottom: 16px;'>
Sample code snippets for consuming PRIMEnergeia outputs in your grid control systems.
</div>
""", unsafe_allow_html=True)

ig1, ig2 = st.columns(2)

with ig1:
    st.markdown("""
    <div class='protocol-card'>
        <div class='section-header' style='color: #00d1ff;'>FILE-BASED INTEGRATION</div>
        <div style='font-size: 15px; font-weight: 600; color: white; margin-top: 4px;'>CSV / JSON Ingest</div>
    </div>
    """, unsafe_allow_html=True)
    st.code("""import pandas as pd

# Load dispatch schedule
dispatch = pd.read_csv("dispatch_schedule_ercot.csv")

# Filter to upcoming charge windows
charge_hours = dispatch[dispatch.Strategy == "CHARGE"]

# Send setpoints to BESS controller
for _, row in charge_hours.iterrows():
    bess.set_power(row.Dispatch_MW, row.Timestamp)
""", language="python")

with ig2:
    st.markdown("""
    <div class='protocol-card'>
        <div class='section-header' style='color: #00ff88;'>API INTEGRATION</div>
        <div style='font-size: 15px; font-weight: 600; color: white; margin-top: 4px;'>REST / WebSocket Feed</div>
    </div>
    """, unsafe_allow_html=True)
    st.code("""import requests

# Fetch latest dispatch from PRIMEnergeia API
resp = requests.get(
    "https://api.primenergeia.com/v1/dispatch",
    headers={"Authorization": "Bearer <token>"},
    params={"market": "ERCOT", "fleet_mw": 100}
)
schedule = resp.json()

# Feed into EMS / SCADA
for point in schedule["dispatch"]:
    scada.write_tag(
        f"PRIME.Dispatch.Hour{point['hour']}",
        point["dispatch_mw"]
    )
""", language="python")

ig3, ig4 = st.columns(2)

with ig3:
    st.markdown("""
    <div class='protocol-card'>
        <div class='section-header' style='color: #FFD700;'>INDUSTRIAL PROTOCOLS</div>
        <div style='font-size: 15px; font-weight: 600; color: white; margin-top: 4px;'>Modbus / DNP3 / IEC 61850</div>
    </div>
    """, unsafe_allow_html=True)
    st.code("""# Modbus TCP — Write dispatch setpoint
from pymodbus.client import ModbusTcpClient

client = ModbusTcpClient("192.168.1.100")
client.connect()

# Register 100 = Active Power Setpoint (MW × 10)
setpoint_mw = dispatch_schedule[current_hour]
client.write_register(100, int(setpoint_mw * 10))

# Register 101 = Mode (0=HOLD, 1=CHARGE, 2=DISCHARGE)
client.write_register(101, mode_code)
client.close()
""", language="python")

with ig4:
    st.markdown("""
    <div class='protocol-card'>
        <div class='section-header' style='color: #8b5cf6;'>BMS INTEGRATION</div>
        <div style='font-size: 15px; font-weight: 600; color: white; margin-top: 4px;'>Battery Management Feed</div>
    </div>
    """, unsafe_allow_html=True)
    st.code("""import json

# Load battery telemetry output
with open("battery_telemetry_ercot.json") as f:
    telemetry = json.load(f)

# Feed SOC targets to BMS
for point in telemetry:
    bms.set_target_soc(point["SOC_pct"])
    bms.update_degradation(
        soh=point["SOH"],
        cycles=point["Cycle_Count_Est"]
    )
    # Trigger maintenance alert if SOH < threshold
    if point["SOH"] < 0.85:
        alert_system.notify("BMS_MAINT_REQUIRED")
""", language="python")

st.divider()

# ═══════════════════════════════════════════════════════════════
#  MARKET SPECIFICATIONS TABLE
# ═══════════════════════════════════════════════════════════════
st.markdown("### 📐 Market Technical Specifications")

specs_df = pd.DataFrame({
    "Parameter": ["Frequency", "Inertia H", "Damping D", "Pricing Model",
                  "Settlement", "THD Standard", "THD Limit",
                  "Penalty Threshold", "Supported Nodes", "Currency"],
    "SEN 🇲🇽": ["60 Hz", "5.0 s", "2.0", "PML (Nodal)",
                "15-min", "Código de Red", "≤5%",
                "±0.05 Hz", "30", "USD/MXN"],
    "ERCOT 🇺🇸": ["60 Hz", "4.5 s", "1.8", "LMP (Nodal)",
                  "5-min RT", "IEEE 519", "≤5%",
                  "±0.03 Hz", "22", "USD"],
    "MIBEL 🇪🇸🇵🇹": ["50 Hz", "6.0 s", "2.5", "OMIE Pool",
                     "Hourly", "EN 50160", "≤8%",
                     "±0.04 Hz", "20", "EUR"],
})
st.dataframe(specs_df, use_container_width=True, hide_index=True)

st.markdown("""
> **17 Global ISOs Supported:** SEN · ERCOT · MIBEL · PJM · CAISO · MISO · SPP · NYISO · ISONE ·
> IESO · AESO · EPEX (DE/FR) · Nord Pool · Elexon · NEM · JEPX
""")

# ═══════════════════════════════════════════════════════════════
#  FOOTER
# ═══════════════════════════════════════════════════════════════
st.divider()
st.caption("PRIMEnergeia S.A.S. — Grid Engineer Outputs Catalog | HJB Dispatch × 17 Global Markets × Integration-Ready")
